### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by jvjvjv** [bhaskardabhi/atom-laravel-log#2]
[Enter steps to reproduce:]

1. Opened Atom (the project for a Laravel application I am developing automatically opened.)

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: [atom-laravel-log](https://github.com/bhaskardabhi/atom-laravel-log) package 0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of null

```
At /Users/jason/.atom/packages/atom-laravel-log/lib/LaravelLogReader.js:59

TypeError: Cannot read property 'map' of null
    at LaravelLogReader.getErrorsWithTime (/packages/atom-laravel-log/lib/LaravelLogReader.js:59:21)
    at /packages/atom-laravel-log/lib/LaravelLogReader.js:26:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

### Commands

```
     -4:19.8.0 window:toggle-full-screen (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-laravel-log 0.2.3 
atom-twig 4.2.0 
auto-indent-file 0.2.0 
ide-vue 0.1.9 
language-blade 0.43.1 
language-nginx 0.8.0 
language-vue 0.25.0 
laravel 0.7.1 
laravel-docs 1.0.3 
```

**Comment by bhaskardabhi** [comment]
Sorry, It took me too long to resolve this issue.
